name: CI/CD Pipeline - Staging

on:
  workflow_run:
    workflows: ["CI/CD Pipeline - Dev"]
    types:
      - completed

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      packages: write
    if: github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Create Build Push Stop
    - name: Login to GitHub
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Start containers
      run: docker-compose -f "docker-compose.dev.yml" build
    - name: Pushing all images
      run: docker-compose -f "docker-compose.dev.yml" push
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.dev.yml" down


  deploy-stagging:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
    # Deploy to Stagging
    - name: Deploy APP to staging
      run: echo ${{ secrets.APIKEY }}
    - name: Echo value
      run: echo ${{ vars.TEST_VALUE }}
