name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: developpement
    permissions:
      contents: read
      packages: write
    # env:
    #   WEB_PATH: ${{ vars.WEB_PATH }}
    #   WEB_PORT: ${{ vars.WEB_PORT }}
    #   NEXT_PUBLIC_API_URL: ${{ vars.URI_NEXT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Start containers
      run: docker-compose -f "docker-compose.dev.yml" build
    - name: Pushing all images
      run: docker-compose -f "docker-compose.dev.yml" push
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.dev.yml" down


  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment: developpement

    steps:
    - name: Deploy APP to dev
      uses: actions/checkout@v2
    - name: print var
      run: echo ${{ secrets.APIKEY }}
    - name: Echo value
      run: echo ${{ vars.TEST_VALUE }}
